name = "live-redirect-worker"
main = "build/worker/shim.mjs"
compatibility_date = "2025-06-07"

[build]
command = "cargo install -q worker-build && ~/.cargo/bin/worker-build --release"

[observability.logs]
enabled = true